### PR TITLE
Add include-dev option to inlcude or not dev packages/path [ #5 ]

### PR DESCRIPTION
**Pull request by MacFJA**

### CODE REVIEW

**Comment by kelunik** [comment]
Didn't have a deeper look, but I think it doesn't work if a package is in require and require dev, could be true for e.g. symfony console.

**Comment by MacFJA** [comment]
I made some tests and this case is handled correctly (thanks to Composer's dependency resolution)

**Comment by kelunik** [comment]
When will you merge / release this?

**Comment by kelunik** [comment]
@MacFJA It's definitely not working correctly. Works with `--include-dev`, but doesn't without.

`PHP Warning:  require(phar:///home/kelunik/GitHub/kelunik/acme-client/build/acme-client.phar/vendor/symfony/polyfill-mbstring/bootstrap.php): failed to open stream: phar error: "vendor/symfony/polyfill-mbstring/bootstrap.php" is not a file in phar "/home/kelunik/GitHub/kelunik/acme-client/build/acme-client.phar" in phar:///home/kelunik/GitHub/kelunik/acme-client/build/acme-client.phar/vendor/composer/autoload_real.php on line 55`

Did you delete your `.phar` during the tests? See #14.

**Comment by MacFJA** [comment]
I found the origin of this.
It's because this file is in a **files** autoloader!
I have to found a way to avoid this error. I have two options:
- always include a package that have a **files** autoloader (easier to implement but will add lots of unuseful files)
- edit the Composer auto-generated file to remove those files from being autoloader (not very clean because i will alter a generated file by Composer)

---

All files declared in a **files** autoloader are always `include` in every _request_ (see [Composer Documentation](https://getcomposer.org/doc/04-schema.md#files))

**Comment by kelunik** [comment]
We could require a path to the composer executable in the configuration if no `--include-dev` is given and execute `composer dumpautoload --no-dev` before packaging. But we should restore the old state then, which will become tricky.

**Comment by MacFJA** [comment]
I'm not really fan of executing _external_ program.

In the commit a2db582, I do a `preg_replace` to remove lines in the `autoload_files.php`.

I try it on you project `kelunik/acme-client` and it work :wink:

**Comment by kelunik** [comment]
Yes, also tried it, works perfectly. :+1: 

Released a new version that includes a `phar` now: https://github.com/kelunik/acme-client/releases/tag/v0.2.3

**Comment by kelunik** [comment]
Time for a new release?

**Pull request merged**
