### PR TITLE
added "skipShebang" to make it possible to skip it

### PR DESCRIPTION
**Pull request by ElectroLutz**
"fixes" issue #24

### CODE REVIEW

**Comment by kelunik** [comment]
I'd like `skipShebang` more. Reflects the default value more.

**Comment by ElectroLutz** [comment]
That's correct...I'm going to change this..give me a minute.

**Comment by ElectroLutz** [comment]
Done. Sorry for the sh*tload of commits.. I somehow was not able to setup git to work with github..(maybe it's the corporate proxy).

**Comment by kelunik** [comment]
Looks like you used the online edit to me. That one creates a new commit per file. Don't worry, GitHub has a squash on merge feature now. :-)

**Pull request merged**
