### PR TITLE
Add fake files for composer dev dependencies

### PR DESCRIPTION
**Pull request by kelunik**
These files are always required by composer, so we just add empty fake files to make it happy.

### CODE REVIEW

**Comment by kelunik** [comment]
@MacFJA Will there be a release with these events soon?

**Comment by MacFJA** [comment]
Adding empty file is not a good solution.
In your example, the file you try to "fake" is a **polyfill** that can be needed in some case (depends on PHP version and installed extension).

Moreover those files must be already handled with the function [MacFJA\PharBuilder\Utils\Composer::readAutoload](https://github.com/kelunik/PharBuilder/blob/master/app/Utils/Composer.php#L81) that also read **classmap** and **files** autoloader

**Comment by kelunik** [comment]
The issue is that it's `dev-only` here, but the Composer autoloader still loads it when no dev packages are packaged.

**Comment by MacFJA** [comment]
Oh, I see. It's because we don't run a `composer dump-autoload --no-dev`.

I'm ok with you code, except that I prefer that the _fake_ addition occurs before the normal addition.
I don't test it but I think that having the _fake_ addition after will erase files if the phar include dev dependency.

**Comment by kelunik** [comment]
That's not an issue. If dev files are included, no stub files are created at all, see https://github.com/MacFJA/PharBuilder/pull/21/files#diff-06addce19c0b973b17f35dd83d3a457fR138

**Pull request merged**
